notes: "This is the main run file for the SkIP model. It uses an transformer based autoencoder to encode and decode the SkIP data. The model is trained using a combination of reconstruction, velocity, and jerk losses.The model is trained on the SkIP dataset."
config:
  resume: false
  resume_from_epoch: 0
  num_epochs: 60
  batch_size: 128

  model:
    d_model: 64
    d_input: 9
    nhead: 8
    num_layers: 4
  
  loss_weights:
    recn_loss: 100
    recn_loss_root_children: 100
    geodesic_loss: 5
    vel_loss: 1
    acc_loss: 0.00001
    root_trajectory_loss: 10
    z_pose_loss: 1
  
  dataset:
    name: "skip"
    path: "/user/kyang2/u12303/skip-dataset"
    train_dir: "train_same_cmu_cleaned"
    test_dir: "test"
    augmentors:
      rest_pose_augmentor:
        max_large_angle: 20
        max_small_angle: 180
      global_skeleton_augmentor:
      x_z_translation_augmentor:
        max_translation: 10