notes: "This is the main run file for the SkIP model. It uses an transformer based autoencoder to encode and decode the SkIP data. The model is trained using a combination of reconstruction, velocity, and jerk losses.The model is trained on the SkIP dataset."
config:
  train:
    num_epochs: 60
    batch_size: 128
    consequtive_frames: 8
    resume: false
    resume_from_epoch: 0
    scheduler:
      warmup_steps: 0
      cycle_mult: 1
      max_lr: 1e-3
      min_lr: 1e-5

  model:
    encoder:
      d_model: 64
      d_input: 18
      nhead: 8
      num_layers: 4
    decoder:
      d_model: 64
      d_input: 6
      nhead: 8
      num_layers: 4
    features:
      - d6
      - position
      - position_prev
      - velocity
      - root_trajectory
  
  loss_weights:
    recn_loss: 100
    recn_loss_root_children: 100
    geodesic_loss: 5
    vel_loss: 1
    acc_loss: 0.00001
    root_trajectory_loss: 10
    z_pose_loss: 1
  
  dataset:
    name: "skip"
    path: "/user/kyang2/u12303/skip-dataset"
    train_dir: "train_same_cmu_cleaned"
    test_dir: "test"
    augmentors:
      rest_pose_augmentor:
        max_large_angle: 20
        max_small_angle: 180
      global_skeleton_augmentor:
      x_z_translation_augmentor:
        max_translation: 10
